### Profile ###

include="~~/profiles.conf"

### Video ###

vo=gpu-next
hwdec=vulkan
gpu-api=vulkan
vd-lavc-dr=yes
hwdec-codecs=all
gpu-context=winvk
#vulkan-device=NVIDIA GeForce RTX 5070 Ti (Specify your gpu)

dither-depth=auto
temporal-dither=yes
dither=error-diffusion
error-diffusion=atkinson

interpolation=no
tscale=oversample
interpolation-preserve
#display-fps-override=180 (Specify if hz is above 60)
#video-sync=display-resample (Enable for high hz display)
tscale-blur=0.6991556596428412

deband=no
	
### Audio and Subtitles ###

slang=en,eng,English,en-US,US
alang=ja,jp,jpn,jap,Japanese,en,eng,English

sub-blur=0.5
sub-gauss=1.5
sub-scale=0.7
sub-margin-y=60
sub-color='#eceff4'
sub-shadow-offset=0
sub-outline-size=1.15
sub-font=Clear Sans Bold
sub-back-color='#2e3440'
sub-border-color='#2e3440'
sub-shadow-color='#2e3440'
sub-outline-color='#2e3440'

sub-auto=all
volume-max=200
sub-fix-timing=yes
blend-subtitles=yes
sub-ass-override=yes  
audio-file-auto=fuzzy 
audio-pitch-correction=yes
audio-normalize-downmix=yes    
audio-channels=7.1,5.1,stereo          
sub-file-paths-append=subtitles
demuxer-mkv-subtitle-preroll=yes
sub-file-paths=sub;subs;subtitles

### Functions ###

osc=no
fs=yes
snap-window
keep-open=yes
save-position-on-quit=yes
watch-later-dir="~~/cache/watch_later"
gpu-shader-cache-dir="~~/cache/shaders_cache"     

### OSD ###

no-border
osd-bar=no
osd-bold=yes
osd-font-size=37
osd-font='JetBrains Mono'